// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/bulk-update': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/bulk-update.post').default>>>>
    }
    '/api/admin/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/categories.get').default>>>>
    }
    '/api/admin/config': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/config.post').default>>>>
    }
    '/api/admin/create-product': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/create-product.post').default>>>>
    }
    '/api/admin/export-orders': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/export-orders.get').default>>>>
    }
    '/api/admin/search-product': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/search-product.get').default>>>>
    }
    '/api/admin/update-product': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/update-product.put').default>>>>
    }
    '/api/admin/upload-image': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/upload-image.post').default>>>>
    }
    '/api/admin/verify-password': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/verify-password.post').default>>>>
    }
    '/api/config': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/config.get').default>>>>
    }
    '/api/product/:slug': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/product/[slug]').default>>>>
    }
    '/api/products': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/index').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
  }
}
export {}