// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 23/4/2026, 13:41:24
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/sebastian-alcantar/WebstormProjects/untitled2/RayForce/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sebastian-alcantar/WebstormProjects/untitled2/RayForce/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sebastian-alcantar/WebstormProjects/untitled2/RayForce/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sebastian-alcantar/WebstormProjects/untitled2/RayForce/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sebastian-alcantar/WebstormProjects/untitled2/RayForce/plugins/**/*.{js,ts,mjs}","/home/sebastian-alcantar/WebstormProjects/untitled2/RayForce/composables/**/*.{js,ts,mjs}","/home/sebastian-alcantar/WebstormProjects/untitled2/RayForce/utils/**/*.{js,ts,mjs}","/home/sebastian-alcantar/WebstormProjects/untitled2/RayForce/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sebastian-alcantar/WebstormProjects/untitled2/RayForce/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/sebastian-alcantar/WebstormProjects/untitled2/RayForce/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/sebastian-alcantar/WebstormProjects/untitled2/RayForce/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;