// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 21/4/2026, 3:47:23 p.m.
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/lanfa/.gemini/antigravity/scratch/Rayforce/RayForce/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/lanfa/.gemini/antigravity/scratch/Rayforce/RayForce/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/lanfa/.gemini/antigravity/scratch/Rayforce/RayForce/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/lanfa/.gemini/antigravity/scratch/Rayforce/RayForce/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/lanfa/.gemini/antigravity/scratch/Rayforce/RayForce/plugins/**/*.{js,ts,mjs}","C:/Users/lanfa/.gemini/antigravity/scratch/Rayforce/RayForce/composables/**/*.{js,ts,mjs}","C:/Users/lanfa/.gemini/antigravity/scratch/Rayforce/RayForce/utils/**/*.{js,ts,mjs}","C:/Users/lanfa/.gemini/antigravity/scratch/Rayforce/RayForce/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/lanfa/.gemini/antigravity/scratch/Rayforce/RayForce/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/lanfa/.gemini/antigravity/scratch/Rayforce/RayForce/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/lanfa/.gemini/antigravity/scratch/Rayforce/RayForce/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;